/**
 * Service-worker registration and the update prompt.
 *
 * The worker (generated by the `pwaAssets` plugin in vite.config.ts) is
 * CACHE-FIRST: the shell is served from the cache without touching the
 * network, which is what makes the installed app open instantly and work with
 * no signal. The cost of cache-first is that a deploy is invisible until a new
 * worker takes over — so the worker deliberately does not `skipWaiting()`, and
 * this module surfaces the choice instead. Swapping the JS bundle underneath a
 * running match is exactly the interruption the cache is meant to avoid.
 *
 * Registration only happens in a production build. A cache-first worker in
 * front of the dev server would serve stale modules and cost an afternoon.
 */

import { button, el } from './dom';
import { t } from './i18n';

/** Query flag that tears the whole thing down; the documented escape hatch. */
const KILL_SWITCH = 'nosw';

/** Minimum gap between foreground update checks. */
const UPDATE_CHECK_INTERVAL_MS = 30 * 60 * 1000;

/**
 * Remove the worker and every cache it owns, then reload clean.
 *
 * This is the answer to the one genuinely scary failure mode of shipping a
 * cache-first worker to a live site: a bad worker that serves a broken shell
 * for ever. `?nosw=1` always wins, because it runs in the page before
 * anything is registered.
 */
async function unregisterEverything(): Promise<void> {
  const regs = await navigator.serviceWorker.getRegistrations();
  await Promise.all(regs.map((r) => r.unregister()));
  if ('caches' in window) {
    const keys = await caches.keys();
    await Promise.all(
      keys.filter((k) => k.startsWith('evo-')).map((k) => caches.delete(k)),
    );
  }
  const url = new URL(location.href);
  url.searchParams.delete(KILL_SWITCH);
  location.replace(url.toString());
}

/**
 * The update bar: one line and one button, top-centre, dismissible.
 *
 * Not a `confirm()` and not automatic — the user may be watching a goal.
 */
function showUpdatePrompt(onAccept: () => void): void {
  if (document.querySelector('.pwa-update')) return;
  const bar = el('div', 'pwa-update');
  const text = el('span', 'pwa-update-text', t('A new version is ready.'));
  const reload = button(t('Update'), onAccept, 'pwa-update-go');
  const dismiss = button('✕', () => bar.remove(), 'pwa-update-dismiss');
  dismiss.title = t('Later');
  bar.append(text, reload, dismiss);
  document.body.appendChild(bar);
}

/**
 * Register the worker and wire the update prompt.
 *
 * Never throws and never blocks startup: offline caching is a bonus, and the
 * game must boot on a browser that refuses the whole API.
 */
export function registerServiceWorker(): void {
  if (!('serviceWorker' in navigator)) return;

  if (new URLSearchParams(location.search).has(KILL_SWITCH)) {
    void unregisterEverything().catch((err) => console.warn('[pwa] teardown failed', err));
    return;
  }

  if (!import.meta.env.PROD) return;

  // Deliberately NOT deferred to `window.load`: this page holds a stadium's
  // worth of audio, so `load` can be minutes away on a phone — the usual
  // "register after load" advice would mean never registering at all in the
  // session that needed it. This module already runs after the game is
  // constructed, and the browser gives a worker install low priority anyway.
  void (async () => {
    try {
      const reg = await navigator.serviceWorker.register('./sw.js');

      // Set only when the USER accepts. `clients.claim()` in the worker fires
      // `controllerchange` on the very first install too, and reloading on
      // that would restart a match nobody asked to restart.
      let reloading = false;
      const accept = (waiting: ServiceWorker) => () => {
        reloading = true;
        waiting.postMessage({ type: 'SKIP_WAITING' });
      };
      navigator.serviceWorker.addEventListener('controllerchange', () => {
        if (reloading) location.reload();
      });

      // An update that finished installing on a previous visit is already
      // waiting when we arrive.
      if (reg.waiting && navigator.serviceWorker.controller) {
        showUpdatePrompt(accept(reg.waiting));
      }

      reg.addEventListener('updatefound', () => {
        const installing = reg.installing;
        if (!installing) return;
        installing.addEventListener('statechange', () => {
          // `controller` present ⇒ this is an UPDATE, not a first install.
          if (installing.state === 'installed' && navigator.serviceWorker.controller) {
            showUpdatePrompt(accept(installing));
          }
        });
      });

      // ASK for the update, don't assume. Calling `register()` again on an
      // existing registration is only a *soft* update in Chromium and gets
      // throttled — measured here: a changed worker sat undetected across a
      // reload for 24s, while an explicit `update()` found it in under one
      // second. Without this, a Pages deploy can go unnoticed indefinitely.
      const checkForUpdate = () => { void reg.update().catch(() => {}); };
      checkForUpdate();
      // Installed apps are long-lived and rarely reloaded, so coming back to
      // the foreground is the natural second checkpoint. Throttled, because
      // app-switching on a phone fires this constantly.
      let lastCheck = Date.now();
      document.addEventListener('visibilitychange', () => {
        if (document.visibilityState !== 'visible') return;
        if (Date.now() - lastCheck < UPDATE_CHECK_INTERVAL_MS) return;
        lastCheck = Date.now();
        checkForUpdate();
      });
    } catch (err) {
      console.warn('[pwa] service worker not registered', err);
    }
  })();
}
