import type { PolicyParams } from '../sim/types';

/**
 * GENERATED by scripts/train-wildcard.ts — do not hand-edit.
 * (μ+λ) ES over PlayerBrain utility weights; genes/squad neutral (0.5).
 * Train: seed 22468, pop 16, 20 gens, panel league 9001.
 * Held-out (league 4242 top-8, home+away): wildcard 12/48 pts vs default 3/48.
 */
export const WILDCARD_POLICY: PolicyParams = {
  "shootBase": 0.9216697027748197,
  "shootGene": 1.8839851013362219,
  "shootModeMul": 1.2652092948853362,
  "shootPressurePen": 0.033725526843859086,
  "passBase": 0.2665996984421072,
  "passLaneW": 0.2421102136889836,
  "passOpenW": 0.1922137313327994,
  "passFwdBase": 0.40384229640276015,
  "passFwdRisk": 0.8661267336628202,
  "passBackPen": 0.35242999344456394,
  "passOutletMul": 1.0944791135298362,
  "dribbleBase": 0.3468813534447585,
  "dribbleSpaceW": 0.6633302176961798,
  "dribbleGeneBase": 0.8259039129518794,
  "dribbleGeneW": 0.6932341828990016,
  "dribblePressurePen": 0.28231854537786905,
  "clearBase": 0.05847291989745343,
  "clearPressureW": 0.5814382636771452,
  "supportBase": 0.28793195954721756,
  "supportProxW": 0.37877679823399807,
  "formationBase": 0.5436112563023898,
  "chaseBase": 0.6208698742787743,
  "markBase": 0.7225299389748008,
  "interceptScore": 0.7669932602638081
};
