import type { PolicyParams } from '../sim/types';

/**
 * GENERATED by scripts/train-wildcard.ts — do not hand-edit.
 * (μ+λ) ES over PlayerBrain utility weights; genes/squad neutral (0.5).
 * Train: seed 22468, pop 16, 20 gens, panel league 9001.
 * Held-out (league 4242 top-8, home+away): wildcard 30/48 pts vs default 9/48.
 */
export const WILDCARD_POLICY: PolicyParams = {
  "shootBase": 1.7715317537019022,
  "shootGene": 1.105395982306007,
  "shootModeMul": 1.1360505865526576,
  "shootPressurePen": 0.2808046137078499,
  "passBase": 0.06363230390991938,
  "passLaneW": 0.2587556304376951,
  "passOpenW": 0.1661051087675838,
  "passFwdBase": 0.2602192268230039,
  "passFwdRisk": 0.9278535541531536,
  "passBackPen": 0.05481430299549997,
  "passOutletMul": 1.024628325822939,
  "dribbleBase": 0.24193138700740913,
  "dribbleSpaceW": 0.531119866222478,
  "dribbleGeneBase": 0.9807221235666463,
  "dribbleGeneW": 1.3790908314308883,
  "dribblePressurePen": 0.390325818347752,
  "clearBase": 0.0853012339937776,
  "clearPressureW": 0.6024129407160141,
  "supportBase": 0.3761452532633849,
  "supportProxW": 0.25252239392096365,
  "formationBase": 0.8,
  "chaseBase": 1.0167922598019454,
  "markBase": 0.5549871006281061,
  "interceptScore": 0.8319017921786146,
  "runScore": 0.9808863545419889,
  "throughBase": 0.45503515195667077,
  "throughOpenW": 0.5271657206106467,
  "throughBehindW": 0.5932197291400447
};
