import type { V2 } from '../utils/vec';
import { BALL_RADIUS, PLAYER_CORE_RADIUS } from './constants';
import {
  directBallAccess,
  recordOwnControlTouch,
  type ActiveControlSequence,
  type BallAccessBody,
  type DirectBallAccess,
  type PhysicalBall,
} from './physical';

export type VirtualFootSide = 'left' | 'right';

export interface VirtualGaitState {
  /** Fraction of distance remaining until the next planned touch. */
  readonly phase: number;
  /** Mirrors ControlSequence.touchIndex; even=left, odd=right. */
  readonly touchIndex: number;
}

export interface VirtualGaitTouch {
  readonly touchIndex: number;
  readonly footSide: VirtualFootSide;
}

export interface VirtualGaitAdvance {
  readonly state: VirtualGaitState;
  readonly touches: readonly VirtualGaitTouch[];
  readonly spacing: number;
}

export interface ControlledTouchContext {
  readonly playerPos: Readonly<V2>;
  readonly playerVel: Readonly<V2>;
  readonly bodyDir: Readonly<V2>;
  readonly ballPos: Readonly<V2>;
  readonly footSide: VirtualFootSide;
  readonly speed: number;
  /** Normalised [0,1] change-of-direction demand. */
  readonly turnDemand: number;
  /** Normalised [0,1] local pressure. */
  readonly pressure: number;
  readonly coreRadius?: number;
  readonly ballRadius?: number;
}

export interface ControlledTouchPlan {
  readonly footAnchor: V2;
  readonly nextTouchTarget: V2;
  readonly horizon: number;
  readonly desiredBallVelocity: V2;
  readonly maxImpulse: number;
}

export interface MutableBallVelocity {
  readonly pos: V2;
  readonly vel: V2;
}

export interface ControlledTouchImpulse {
  readonly impulse: V2;
  readonly magnitude: number;
  readonly velocityAfter: V2;
}

export interface ControlLeaseContactInput {
  readonly sequence: ActiveControlSequence;
  readonly actor: BallAccessBody;
  readonly controllerSide: 0 | 1;
  readonly ball: PhysicalBall;
  readonly bodies: readonly BallAccessBody[];
  readonly maxCenterReach: number;
  readonly tick: number;
}

export type ControlLeaseContactResult =
  | {
      readonly kind: 'noContact';
      readonly sequence: ActiveControlSequence;
      readonly access: DirectBallAccess;
      readonly handoff: null;
    }
  | {
      readonly kind: 'ownTouch';
      readonly sequence: ActiveControlSequence;
      readonly access: DirectBallAccess;
      readonly handoff: null;
    }
  | {
      readonly kind: 'opponentContact';
      readonly sequence: ReturnType<typeof breakControlSequenceOnOpponentContact>;
      readonly access: DirectBallAccess;
      /** The existing M3 contact→control process is the only next resolver. */
      readonly handoff: 'm3';
    };

const clamp01 = (value: number): number => Math.max(0, Math.min(1, value));

const unitOrX = (value: Readonly<V2>): V2 => {
  const length = Math.hypot(value.x, value.y);
  return length > 1e-8 ? { x: value.x / length, y: value.y / length } : { x: 1, y: 0 };
};

export function virtualFootForTouch(touchIndex: number): VirtualFootSide {
  return Math.abs(Math.trunc(touchIndex)) % 2 === 0 ? 'left' : 'right';
}

/**
 * Distance travelled per planned close-control touch. Cadence is generated by
 * locomotion distance; pressure/turn demand compress the stride rather than
 * introducing an independent timer.
 */
export function controlledTouchSpacing(
  speed: number,
  turnDemand: number,
  pressure: number,
): number {
  const base = 0.82 + Math.min(Math.max(speed, 0), 7) * 0.2;
  const compression = 1 - clamp01(turnDemand) * 0.12 - clamp01(pressure) * 0.14;
  return Math.max(0.55, base * compression);
}

/** Advance the virtual gait using distance only; zero travel means zero touch. */
export function advanceVirtualGait(
  state: VirtualGaitState,
  distanceTravelled: number,
  speed: number,
  turnDemand: number,
  pressure: number,
): VirtualGaitAdvance {
  const spacing = controlledTouchSpacing(speed, turnDemand, pressure);
  const raw = Math.max(0, state.phase) + Math.max(0, distanceTravelled) / spacing;
  const touchCount = Math.floor(raw + 1e-12);
  const touches: VirtualGaitTouch[] = [];
  for (let index = 0; index < touchCount; index++) {
    const touchIndex = state.touchIndex + index;
    touches.push({ touchIndex, footSide: virtualFootForTouch(touchIndex) });
  }
  return {
    state: {
      phase: raw - touchCount,
      touchIndex: state.touchIndex + touchCount,
    },
    touches,
    spacing,
  };
}

/** Query point only: never a collider, magnet or authoritative ball position. */
export function virtualFootAnchor(
  playerPos: Readonly<V2>,
  bodyDir: Readonly<V2>,
  footSide: VirtualFootSide,
  coreRadius = PLAYER_CORE_RADIUS,
  ballRadius = BALL_RADIUS,
): V2 {
  const forward = unitOrX(bodyDir);
  const lateralSign = footSide === 'left' ? 1 : -1;
  const forwardOffset = coreRadius + ballRadius + 0.08;
  const lateralOffset = 0.16 * lateralSign;
  return {
    x: playerPos.x + forward.x * forwardOffset - forward.y * lateralOffset,
    y: playerPos.y + forward.y * forwardOffset + forward.x * lateralOffset,
  };
}

/**
 * Plan one real velocity-only micro-touch toward the next recoverable foot
 * point. The target follows the player's predicted displacement over a bounded
 * horizon; no position write or possession transition occurs here.
 */
export function planControlledTouch(context: ControlledTouchContext): ControlledTouchPlan {
  const turnDemand = clamp01(context.turnDemand);
  const pressure = clamp01(context.pressure);
  const spacing = controlledTouchSpacing(context.speed, turnDemand, pressure);
  const horizon = Math.max(0.22, Math.min(0.58, spacing / Math.max(context.speed, 1.5)));
  const futurePlayerPos = {
    x: context.playerPos.x + context.playerVel.x * horizon,
    y: context.playerPos.y + context.playerVel.y * horizon,
  };
  const nextFootSide: VirtualFootSide = context.footSide === 'left' ? 'right' : 'left';
  const fullAnchor = virtualFootAnchor(
    futurePlayerPos,
    context.bodyDir,
    nextFootSide,
    context.coreRadius,
    context.ballRadius,
  );
  const forward = unitOrX(context.bodyDir);
  const footAnchor = virtualFootAnchor(
    context.playerPos,
    context.bodyDir,
    context.footSide,
    context.coreRadius,
    context.ballRadius,
  );
  // Under pressure the target narrows toward the body's forward line while
  // preserving the same authoritative ball and alternating touch side.
  const lateralScale = 1 - pressure * 0.35 - turnDemand * 0.15;
  const dx = fullAnchor.x - futurePlayerPos.x;
  const dy = fullAnchor.y - futurePlayerPos.y;
  const forwardPart = dx * forward.x + dy * forward.y;
  const lateralX = dx - forward.x * forwardPart;
  const lateralY = dy - forward.y * forwardPart;
  const nextTouchTarget = {
    x: futurePlayerPos.x + forward.x * forwardPart + lateralX * lateralScale,
    y: futurePlayerPos.y + forward.y * forwardPart + lateralY * lateralScale,
  };
  const desiredBallVelocity = {
    x: (nextTouchTarget.x - context.ballPos.x) / horizon,
    y: (nextTouchTarget.y - context.ballPos.y) / horizon,
  };
  return {
    footAnchor,
    nextTouchTarget,
    horizon,
    desiredBallVelocity,
    maxImpulse: 4 + Math.max(0, context.speed) * 0.9,
  };
}

/** Apply a bounded impulse to velocity only. `ball.pos` is never written. */
export function applyControlledTouchImpulse(
  ball: MutableBallVelocity,
  plan: ControlledTouchPlan,
): ControlledTouchImpulse {
  const dx = plan.desiredBallVelocity.x - ball.vel.x;
  const dy = plan.desiredBallVelocity.y - ball.vel.y;
  const desiredMagnitude = Math.hypot(dx, dy);
  const magnitude = Math.min(desiredMagnitude, Math.max(0, plan.maxImpulse));
  const scale = desiredMagnitude > 1e-8 ? magnitude / desiredMagnitude : 0;
  const impulse = { x: dx * scale, y: dy * scale };
  ball.vel.x += impulse.x;
  ball.vel.y += impulse.y;
  return {
    impulse,
    magnitude,
    velocityAfter: { x: ball.vel.x, y: ball.vel.y },
  };
}

/** Break the lease only; this never assigns the ball to the opponent. */
export function breakControlSequenceOnOpponentContact(
  sequence: ActiveControlSequence,
  tick: number,
) {
  return {
    ...sequence,
    status: 'broken' as const,
    endedTick: tick,
    breakCause: 'opponentContact' as const,
  };
}

/**
 * B1c-2 boundary: geometry proves a real contact before sequence semantics
 * react. The controller's own contact advances the same lease; an opponent's
 * contact breaks it and hands the physical event to M3. Proximity alone and
 * deferred teammate transfers do neither.
 */
export function resolveControlLeaseContact(
  input: ControlLeaseContactInput,
): ControlLeaseContactResult {
  const access = directBallAccess(input.actor, input.ball, input.bodies, input.maxCenterReach);
  if (!access.canDirectlyContact) {
    return { kind: 'noContact', sequence: input.sequence, access, handoff: null };
  }
  if (input.actor.gid === input.sequence.controllerGid) {
    return {
      kind: 'ownTouch',
      sequence: recordOwnControlTouch(input.sequence, input.tick),
      access,
      handoff: null,
    };
  }
  if (input.actor.side !== input.controllerSide) {
    return {
      kind: 'opponentContact',
      sequence: breakControlSequenceOnOpponentContact(input.sequence, input.tick),
      access,
      handoff: 'm3',
    };
  }
  return { kind: 'noContact', sequence: input.sequence, access, handoff: null };
}
